import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      {/* <body className="bg-gradient-to-r from-violet-300 via-purple-300 to-indigo-300 bg-animate">{children}</body> */}

    </html>
  )
}
